[package]
authors = [
    "Gerd Zellweger <mail@gerdzellweger.com>",
    "Eric Kidd <git@randomhacks.net>",
    "Philipp Oppermann <dev@phil-opp.com>",
    "Dan Schatzberg <schatzberg.dan@gmail.com>",
    "John Ericson <John_Ericson@Yahoo.com>",
    "Rex Lunae <rexlunae@gmail.com>",
]
description = "Support for x86_64 specific instructions, registers, and structures."
documentation = "https://docs.rs/x86_64"
keywords = [
    "amd64",
    "x86",
    "x86_64",
    "no_std",
]
categories = [
    "no-std",
]
license = "MIT/Apache-2.0"
name = "x86_64"
readme = "README.md"
repository = "https://github.com/rust-osdev/x86_64"
version = "0.6.0"
edition = "2018"

[dependencies]
bit_field = "0.9.0"
bitflags = "1.0.4"
array-init = "0.0.4"
x86_64_types = { git = "https://github.com/rust-osdev/x86_64_types" }

[dependencies.cast]
version = "0.2.2"
default-features = false

[target.'cfg(target_arch = "x86_64")'.dependencies]
raw-cpuid = "6.1.0"

[dependencies.ux]
default-features = false
version = "0.1.3"

[features]
deny-warnings = []
